### PR TITLE
Switch to TestNet2

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Review by jcvernaleo — CHANGES_REQUESTED** [review]
Could you mention the addition of the seeders to in the commit?

**Comment by jcvernaleo** [comment]
Looks correct but probably should wait until things are all good before this goes in.

**Comment by dajohi** [comment]
Updated commit message.

**Review by jcvernaleo — APPROVED** [review]

**Comment by jcvernaleo** [comment]
Not sure how this slipped by me.  All good to go in.

**Pull request merged**
