### PR TITLE
Fix PrivateKey.toWIF

### PR DESCRIPTION
**Pull request by fanatid**
to wif in dcrd -- https://github.com/decred/dcrutil/blob/883bcecb86cda037f14a22ef923a5ea79f751512/wif.go#L124

### CODE REVIEW

**Comment by jcvernaleo** [comment]
This looks good to me.  @alexlyp you touched this last so do you agree?

**Comment by alexlyp** [comment]
Ya should be fine i think, don't believe we use any of that functionality in the copay/insight stack

**Comment by fanatid** [comment]
Thank you.

**Comment by peterzen** [comment]
The multisig wallet creation in Copay relies on `toWIF`; this change causes `bitcore` to generate an invalid secret.

[bitcore-wallet-client](https://github.com/decred/bitcore-wallet-client/blob/master/lib/api.js#L1216-L1236)

https://github.com/decred/bitcore-wallet-client/issues/11

**Comment by alexlyp** [comment]
In lieu of @peterzen's findings I will be reverting this PR

**Pull request merged**
